import SingleNote from '@/components/SingleNote';
import { useAppDispatch, useAppSelector } from '@/hooks/redux';
import { Note } from '@/interfaces/note.interface';
import { setNotes } from '@/store/slices/notes.slice';
import { Inter } from '@next/font/google';
import axios from 'axios';
import jwtDecode from 'jwt-decode';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

interface DecodedToken {
  exp: number;
}

export default function Home() {
  const notes = useAppSelector((state) => state.notes);
  const user = useAppSelector((state) => state.user);
  const dispatch = useAppDispatch();
  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem('token');

    if (token) {
      const decodedToken = jwtDecode<DecodedToken>(token);
      const currentTime = Date.now() / 1000;
      if (!decodedToken.exp) {
        throw new Error('Token has no expiration date');
      }
      if (decodedToken.exp < currentTime) {
        localStorage.removeItem('token');
      }
    }
  }, []);

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) return;

    const fetchNotes = async () => {
      try {
        const { data } = await axios.get<Note[]>(
          `http://localhost:5000/api/notes/user/${user.user?._id}}`
        );
        dispatch(setNotes({ notes: data }));
      } catch (error) {
        console.error(error);
      }
    };
    fetchNotes();
    router.push(`/${user.user?._id}/notes`);
  }, [dispatch, user, router]);

  return (
    <>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        {notes.notes?.length > 0 &&
          notes.notes?.map((note: Note) => {
            return <SingleNote key={note._id} note={note} />;
          })}
      </main>
    </>
  );
}
